#服务配置
server:
  port: 9001
#spring配置
spring:
  profiles:
    active: dev
  #1.应用配置
  application:
    name: ihrm-company #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple4j?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: simple4j
    password: simple4j

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl