#服务配置
server:
  port: 9002
#spring配置
spring:
  profiles:
    active: dev
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple4j?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: simple4j
    password: simple4j
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis-plus:
  mapper-locations: classpath:/mapping/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath:mapper/*.xml, classpath:mybatis/mapping/**/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.spring.**
  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
#    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
#    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
#    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
#    sql-parser-cache: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

jwt:
  config:
    key: simple4j
    ttl: 3600000

security:
  jwt:
    token:
      secret-key: simple4j.simple4code.com
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      prefix: Bearer
      header: Authorization
#自定义参数，可以迁移走
token:
  #token失效时间（不是refreshToken）(这是自定义的)(秒)
  expirationSeconds: 300

  #默认7天登录有效(根据业务更改)
  validTime: 7