spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple4j?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: simple4j
    password: simple4j
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    database: 6
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0


swagger:
  production: true