spring:
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  jwt:
    token:
      secret-key: simple4j.simple4code.com
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      prefix: Bearer_
      header: Authorization